//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Services.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        public int S_No { get; set; }

        [Required(ErrorMessage ="This Field is required")]
        [DisplayName("Admin Id")]
        public string Admin_Id { get; set; }




        [Required(ErrorMessage = "This Field is required")]
        [DataType(DataType.Password)]
        [DisplayName("Admin Password")]
        public string Admin_Password { get; set; }


        public string LoginErrorMessage { get; set; }
    }
}
