//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Services.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin()
        {
            this.Feedback_Details = new HashSet<Feedback_Details>();
        }

        public int S_No { get; set; }

        [Required(ErrorMessage = "This Field is required")]
        [DisplayName("Admin Id")]
        public string Admin_Id { get; set; }




        [Required(ErrorMessage = "This Field is required")]
        [DataType(DataType.Password)]
        [DisplayName("Admin Password")]
        public string Admin_Password { get; set; }


        public string LoginErrorMessage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback_Details> Feedback_Details { get; set; }
    }
}
