//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_Details
    {
        public int Payment_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Booking_Id { get; set; }
        public Nullable<int> Vendor_Id { get; set; }
        public Nullable<int> Service_Id { get; set; }
        public string Price { get; set; }
        public string Booking_Status { get; set; }
        public string Payment_Status { get; set; }
    
        public virtual Booking_Details Booking_Details { get; set; }
        public virtual Vendor_Service_Details Vendor_Service_Details { get; set; }
        public virtual User_Registration User_Registration { get; set; }
        public virtual Vendor_Registration Vendor_Registration { get; set; }
    }
}
