//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking_Details()
        {
            this.Bill_Details = new HashSet<Bill_Details>();
        }
    
        public int Booking_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Service_Id { get; set; }
        public string Price { get; set; }
        public string User_Name { get; set; }
        public string Start_Time { get; set; }
        public string End_Time { get; set; }
        public string Customer_Address { get; set; }
        public Nullable<int> Vendor_Id { get; set; }
    
        public virtual Vendor_Service_Details Vendor_Service_Details { get; set; }
        public virtual User_Registration User_Registration { get; set; }
        public virtual Vendor_Registration Vendor_Registration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Details> Bill_Details { get; set; }
    }
}
