//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback_Details
    {
        public int Feedback_Id { get; set; }
        public Nullable<int> Admin_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Vendor_Id { get; set; }
        public string Feedback { get; set; }
        public string Rating { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual User_Registration User_Registration { get; set; }
        public virtual Vendor_Registration Vendor_Registration { get; set; }
    }
}
