//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Services.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User_Registration
    {
        public int User_Id { get; set; }
        
        
        [Required]
        [Display(Name = "First Name")]
        public string First_Name { get; set; }
        
        [Required]
        [Display(Name = "Last Name")]
        public string Last_Name { get; set; }
        
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
        
        [Required]
        [Display(Name ="Date Of Birth")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true , DataFormatString ="{0:MM/dd/yyyy}")]
        public string DOB { get; set; }
        
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        
        [Required]
        [DataType(DataType.Password)]
        [Compare("Password")]
        [Display(Name = "Confirm Password")]
        public string Confirm_Password { get; set; }
        
        [Required]
        [Display(Name = "Contact Number")]
        public string Contact_Number { get; set; }

        public string LoginErrorMessage { get; set; }
    }

}
