//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_Service_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor_Service_Details()
        {
            this.Booking_Details = new HashSet<Booking_Details>();
            this.Bill_Details = new HashSet<Bill_Details>();
        }
    
        public int Vendor_Id { get; set; }
        public int Service_Id { get; set; }
        public string Service_Name { get; set; }
        public string Price { get; set; }
        public string Start_Time { get; set; }
        public string End_Time { get; set; }
        public string Map_Details { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_Details> Booking_Details { get; set; }
        public virtual Vendor_Registration Vendor_Registration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Details> Bill_Details { get; set; }
    }
}
