//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Services.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class Vendor_Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor_Registration()
        {
            this.Booking_Details = new HashSet<Booking_Details>();
            this.Feedback_Details = new HashSet<Feedback_Details>();
            this.Vendor_Service_Details = new HashSet<Vendor_Service_Details>();
            this.Bill_Details = new HashSet<Bill_Details>();
        }

        public int Vendor_Id { get; set; }

        [Required(ErrorMessage = "This Feild is Required")]
        [DisplayName("First Name")]
        public string First_Name { get; set; }


        [Required(ErrorMessage = "This Feild is Required")]
        [DisplayName("Last Name")]
        public string Last_Name { get; set; }


        [Required(ErrorMessage = "This Feild is Required")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        [DisplayName("Date of Birth")]
        public string DOB { get; set; }
        public string LoginErrorMessage { get; set; }



        [Required(ErrorMessage = "This Feild is Required")]

        public string Gender { get; set; }


        [Required(ErrorMessage = "This Feild is Required")]
        [DisplayName("Contact Number")]
        [DataType(DataType.PhoneNumber)]
        public string Contact_Number { get; set; }


        [Required(ErrorMessage = "This Feild is Required")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required(ErrorMessage = "This Feild is Required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "This Feild is Required")]
        [DisplayName("Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }

       

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_Details> Booking_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback_Details> Feedback_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendor_Service_Details> Vendor_Service_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Details> Bill_Details { get; set; }
    }
}
